name: 'Build: Manual'

on:
  workflow_dispatch:
    inputs:
      bundler:
        type: choice
        description: Bundler
        required: true
        options:
          - app-vite
          - app-webpack
          - app-esbuild
      build_environment:
        type: choice
        description: Build Environment
        required: true
        options:
          - development
          - staging
          - production

env:
  HUSKY: 0

jobs:
  build:
    name: Manual - Lint, Build and Test
    timeout-minutes: 15
    runs-on: ubuntu-latest
    # To use Remote Caching, uncomment the next lines and follow the steps below.
    # env:
    #  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
    #  TURBO_TEAM: ${{ vars.TURBO_TEAM }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Build project
        uses: ./.github/actions/build-project
        with:
          build-filter: ${{ github.event.inputs.bundler }}
          build-environment: ${{ github.event.inputs.build_environment }}
          check-dependencies: 'true'
          check-format: 'true'
          run-lint: 'true'
          run-tests: 'true'
