name: 'Build: Manual'

on:
  workflow_dispatch:
    inputs:
      bundler:
        type: choice
        description: Bundler
        required: false
        # default: default
        options:
          - all
          - default
          - app-vite
          - app-webpack
          - app-esbuild
      build_environment:
        type: choice
        description: Build Environment
        required: true
        options:
          - development
          - staging
          - production

env:
  HUSKY: 0

jobs:
  build:
    name: Manual - Lint, Build and Test
    timeout-minutes: 15
    runs-on: ubuntu-latest
    # To use Remote Caching, uncomment the next lines and follow the steps below.
    # env:
    #  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
    #  TURBO_TEAM: ${{ vars.TURBO_TEAM }}

    steps:
      - name: Set BUNDLER environment variable
        run: |
          if [ "${{ github.event.inputs.bundler }}" == "all" ]; then
            echo "BUNDLER=" >> $GITHUB_ENV
          elif [ "${{ github.event.inputs.bundler }}" == "default" ]; then
            echo "BUNDLER=${{ vars.DEFAULT_BUNDLER }}" >> $GITHUB_ENV
          elif [ -n "${{ github.event.inputs.bundler }}" ]; then
            echo "BUNDLER=${{ github.event.inputs.bundler }}" >> $GITHUB_ENV
          else
            echo "BUNDLER=${{ vars.DEFAULT_BUNDLER }}" >> $GITHUB_ENV
          fi

      - name: DEBUG
        run: |
          echo "BUNDLER: $BUNDLER"
          echo "inputs.bundler: ${{ github.event.inputs.bundler }}"
          echo "github.event.inputs.bundler == 'all': ${{ github.event.inputs.bundler == 'all' }}"

      - name: Check DEFAULT_BUNDLER
        if: ${{ !vars.DEFAULT_BUNDLER }}
        run: |
          echo "::warning::DEFAULT_BUNDLER variable is not set."

      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Build project
        uses: ./.github/actions/build-project
        with:
          build-filter: ${{ env.BUNDLER }}
          build-environment: ${{ github.event.inputs.build_environment }}
          check-dependencies: 'true'
          check-format: 'true'
          run-lint: 'true'
          run-tests: 'true'
