name: 'Deploy: AWS: Infrastructure'

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: dev
        type: choice
        options:
          - dev
          - staging
          - prod

concurrency:
  # Unique group for each workflow + branch + environment + infra action
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event.inputs.environment }}-infra
  cancel-in-progress: true # Cancel any in-progress runs for this group

env:
  AWS_DEFAULT_REGION: us-east-1

permissions:
  id-token: write
  contents: write
  issues: write
  pull-requests: write

jobs:
  deploy-infra:
    runs-on: ubuntu-latest

    # map input environment to GitHub environment
    environment: >-
      ${{
        github.event.inputs.environment == 'dev' && 'development' ||
        github.event.inputs.environment == 'staging' && 'staging' ||
        'production'
      }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy infrastructure to ${{ github.event.inputs.environment }}
        uses: ./infra/aws-deploy/.github/actions/deploy
        with:
          environment: ${{ github.event.inputs.environment }}
          action: infra
          aws-role-arn: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}
